const constants = {
    accept: "Aceptar",
    addBlock: "Añadir bloque",
    addBlockText: "Seleccione la plantilla de bloque a añadir",
    addCycle: "Añadir mesociclo",
    addExercise: "Añadir ejercicio",
    addToCalendar: "Añadir al calendario",
    admin: "Admin",
    adminView: "Vista Admin",
    assignation: "Asignación",
    block: "Bloque",
    blocks: "Bloques",
    templates: "Plantillas",
    cancel: "Cancelar",
    calendar: "Calendario",
    chat: "Chat",
    color: "Color",
    createBlock: "Crear bloque",
    createExercise: "Crear ejercicio",
    createUser: "Crear usuario",
    createUserText: "Al crear un nuevo usuario se le asignará una contraseña aleatoria. Una vez creado seleccione la opción de " +
    "'Enviar email de recuperación de contraseña' para que pueda acceder a la aplicación con su conraseña nueva.",
    cycle: "Mesociclo",
    cycles: "Mesociclos",
    dateFormat: "DD-MM-YYYY",
    delete: "Eliminar",
    deleteCycleText: "El mesociclo será eliminado permantentemente de la base de datos y será imposible revertir esta acción.",
    deleteCycleQuestion: "¿Eliminar mesociclo permanentemente?",
    deleteUser: "Eliminar usuario",
    deleteUserText: "El usuario será eliminado permantentemente de la base de datos y será imposible revertir esta acción.",
    deleteUserQuestion: "¿Eliminar usuario permanentemente?",
    disabled: "inhabilitado",
    disableUser: "Inhabilitar usuario",
    edit: "Editar",
    enableUser: "Habilitar usuario",
    end: "Final",
    endHelper: "Momento en el que forzar el final del vídeo, en segundos",
    email: "Correo electrónico",
    exercise: "Ejercicio",
    exercises: "Ejercicios",
    fromTemplate: "Desde plantilla",
    fromScratch: "Desde cero",
    name: "Nombre",
    noResults: "No hay resultados...",
    login: "Login",
    loginError: "Error: mail o contraseña incorrectos",
    logout: "Cerrar sesión",
    password: "Contraseña",
    reports: "Reportes",
    search: 'Buscar',
    sendPasswordRetrievingEmail: "Enviar email de recuperación de contraseña",
    setAsSuperadmin: "Dar privilegios de Súper Admin",
    setAsAdmin: "Dar privilegios de Admin",
    setAsUser: "Dar privilegios de Usuario",
    signin: "Entrar",
    shortName: "Abreviatura",
    start: "Cominezo",
    startHelper: "Momento en el que forzar el comienzo del vídeo, en segundos",
    superAdmin: "Súper Admin",
    tools: "Herramientas",
    user: "Usuario",
    users: "Usuarios",
    videoId: "YouTube Id",
    videoIdHelper: "Id del vídeo, no la URL entera. P. ej.: KnoncdQSzp0",
    userView: "Vista Usuario",
    weekDays: ["LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB", "DOM"],
}

export default constants;