const constants = {
    accept: "Aceptar",
    addBlock: "Crear bloque",
    addExercise: "Crear ejercicio",
    addUser: "Crear usuario",
    addUserText: "Al crear un nuevo usuario se le asignará una contraseña aleatoria. Una vez creado seleccione la opción de " +
    "'Enviar email de recuperación de contraseña' para que pueda acceder a la aplicación con su conraseña nueva.",
    admin: "Admin",
    adminView: "Vista Admin",
    blocks: "Bloques",
    blueprints: "Plantillas",
    cancel: "Cancelar",
    calendar: "Calendario",
    chat: "Chat",
    dateFormat: "DD-MM-YYYY",
    deleteUser: "Eliminar usuario",
    deleteUserText: "El usuario será eliminado permantentemente de la base de datos y será imposible revertir esta acción.",
    deleteUserQuestion: "¿Eliminar usuario permanentemente?",
    disabled: "inhabilitado",
    disableUser: "Inhabilitar usuario",
    enableUser: "Habilitar usuario",
    email: "Correo electrónico",
    exercises: "Ejercicios",
    login: "Login",
    loginError: "Error: mail o contraseña incorrectos",
    logout: "Cerrar sesión",
    password: "Contraseña",
    search: 'Buscar',
    sendPasswordRetrievingEmail: "Enviar email de recuperación de contraseña",
    setAsSuperadmin: "Dar privilegios de Súper Admin",
    setAsAdmin: "Dar privilegios de Admin",
    setAsUser: "Dar privilegios de Usuario",
    signin: "Entrar",
    superAdmin: "Súper Admin",
    tools: "Herramientas",
    user: "Usuario",
    users: "Usuarios",
    userView: "Vista Usuario",
    weekDays: ["LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB", "DOM"],
}

export default constants;